# Поддержка версии Python
target-version = "py314"
 
# Основные настройки
line-length = 88 # Максимальная длина строки для кода
indent-width = 4 # Ширина отступа
 
# Каталоги, которые следует учитывать при разрешении импорта из first/third-party источников
src = ["backend/*"]
exclude = [
    "venv",
    "**/migrations/**",
]
 
# Настройки линтера
[lint]
# Нестабильные и находящиеся в предварительной версии правила
preview = true
# Правила, которые должен применять линтер
select = [
    "UP",   # pyupgrade
    "I",    # isort
    "E",    # flake8-errors
    "W",    # flake8-warnings
    "F",    # flake8-pyflakes
    "B",    # flake8-bugbear
    "C4",   # flake8-comprehensions
    "N",    # pep8-naming (N)
    "S",    # flake8-bandit
    "BLE",  # flake8-blind-except
    "T20",  # flake8-print
    "T10",  # flake8-debugger
    "PT",   # flake8-pytest-style
    "PL",   # Pylint
    "RUF",  # Ruff
    "ERA",  # eradicate
    "FURB", # refurb
]
# Игнорирование конкретных предупреждений линтера
ignore = [
    "C408",  # Ненужный вызов dict, list и т.д.
    "RUF001", # Игнорирование похожих символов с разными ASCII
    "RUF002", # Игнорирование похожих символов с разными ASCII
    "RUF003", # Игнорирование похожих символов с разными ASCII
    "S110",  # try-except-pass
    "BLE001",
    "PLR6301",
]
# Исключение директорий и файлов из линтинга
exclude = []
# Ошибки, которые могут быть исправлены автоматически
fixable = [
    "ALL",
]
 
# Настройки форматтера
[format]
quote-style = "double"
indent-style = "space"
 
# Дополнительные настройки для плагинов
[lint.flake8-bandit]
check-typed-exception = true # Проверка типизированных исключений

[lint.per-file-ignores]
"docs/**.py" = ["F403", "F405", "E501"]
"**/__init__.py" = ["F403", "F405"]
"**/views.py" = ["PLR6301"]
"**/serializers.py" = ["PLR6301"]
"**/filters.py" = ["PLR6301"]
"**/admin.py" = ["PLR6301"]
"core/asgi.py" = ["E402"]
